---
kind: pipeline
name: drone-php7

platform:
  os: linux
  arch: amd64

# GIT CLONE SECTION #
git-clone:
  git:
    image: plugins/git:next

# WORKSPACE #
workspace:
  base: /test
  path: toolkit

# SERVICES #
services:
  - name: web
    image: fpfis/httpd-php-dev
    environment:
      DOCUMENT_ROOT: /test/toolkit/build
      PORT: 8080

  - name: mysql
    image: fpfis/mysql56
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_MAX_ALLOWED_PACKET: 128M

# BUILD SECTION #
steps:
  # SETUP TOOLKIT #
  - name: toolkit
    image: fpfis/httpd-php-dev
    commands:
      - composer install
      - rm -rf ./.tmp/ ./build

  # TELEGRAM NOTIFICATIONS
  - name: notification
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      message: >
        {{#success build.status}}
          ✅ Build succeeded #{{build.number}} of '{{repo.name}}' - Good job!
          Commit {{commit.sha}} by {{commit.author}} on '{{commit.branch}}':
          {{commit.message}} - See on Github: {{commit.link}}
        {{else}}
          ❌ Build failed #{{build.number}} of '{{repo.name}}' - Fix it please.
          Commit {{commit.sha}} by {{commit.author}} on '{{commit.branch}}':
          {{commit.message}} - See on Github: {{commit.link}}
        {{/success}}